### ISSUE TITLE
迷惑行为？

### ISSUE THREAD

**Issue by purofle** [Otherside-devup/leg#4]
https://github.com/Otherside-devup/leg/blob/bb8e92cd9556b6139d80f0e1250110742902eaaa/mod/leg_search.py#L4

**Comment by WorldMoZara** [comment]
单独使用和被调用使用之间的差异暂时没有比较妥善的办法。

**Comment by WorldMoZara** [comment]
你可以分别在两个import后面写上几个print语句。看看在两种情况下，分别执行哪一个。

**Comment by WorldMoZara** [comment]
不过我觉得可以利用一下`if __name__ == '__main__':`来改进这种情况。
